# Generated by Django 2.1.15 on 2020-05-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Pag',
        ),
    ]
