# Generated by Django 2.1.15 on 2020-05-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200524_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pag',
            new_name='Tag',
        ),
    ]
